### ISSUE TITLE
white rectagle in some scenaries

### ISSUE THREAD

**Issue by SJK9906** [BelmuTM/Noble#12]
what is this white rectangle?
this problem (if this a problem) there is in render mode or in default mode
images with shader
![image](https://github.com/BelmuTM/Noble/assets/129201282/23563af0-fc24-4436-ad15-7ccac211c3dc)
![image](https://github.com/BelmuTM/Noble/assets/129201282/04f759a2-0c7c-465a-99d3-bcf8846b47a1)
![image](https://github.com/BelmuTM/Noble/assets/129201282/d2c2ad19-62db-4779-bc89-90b9d6fcd0fb)

images without shader
![image](https://github.com/BelmuTM/Noble/assets/129201282/c06a9b9b-0fe0-4e14-9ebf-9eca3ad0c55e)
![image](https://github.com/BelmuTM/Noble/assets/129201282/64b1f540-def6-4aa1-8fba-b99245a6e923)
![image](https://github.com/BelmuTM/Noble/assets/129201282/fc0db3a6-4462-46d9-a4b4-ef55694e2e22)

**Comment by BelmuTM** [comment]
Hey, try using a version of Iris that's below 1.7, thanks!

**Comment by SJK9906** [comment]
i'm correnting using iris 1.6.17 with minecraft 1.20.4, nobleRT 1.6.4 and Tlouncher 2.899
OS and hardware info:
CPU: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz   3.60 GHz
RAM: 16,0 GB (15,8 GB usable)
GPU info:

Resoconto delle informazioni di sistema NVIDIA creato il: 03/16/2024 13:21:38
Versione app NVIDIA: 10.0.0.505/p
Sistema operativo: Microsoft Windows 11 Pro, Versione 10.0.22631
Versione runtime DirectX: DirectX 12

Scheda grafica
graphi processor GPU: NVIDIA GeForce RTX 3060
function level Direct3D: 12_1
cuda Cores: 3584
graphic clock: 1837 MHz
Barra ridimensionabile: No
Frequenza dati di memoria: 15.00 Gbps
Interfaccia memoria: 192 bit
Larghezza di banda memoria: 360.048 GB/s
Memoria grafica totale disponibile: 20396 MB
Memoria video dedicata: 12288 MB GDDR6
Memoria video di sistema: 0 MB
Memoria di sistema condivisa: 8108 MB
video BIOS version: 94.06.2f.00.9d
IRQ: not used
bus: PCI Express x16 Gen4
device ID: 10DE ---- --------
article code: G190 ----

Driver: Driver Game Ready - 551.61 - Feb 22, 2024
Schermo: 1920x1080,60Hz
CPU: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz
RAM: 16.0 GB
Archiviazione: SSD - 931.5 GB


windows info:
Exsperience: Windows Feature Experience Pack 1000.22687.1000.0
edtion: Windows 11 Pro
versione: 23H2
build: 22631.3296

mod:
iris-mc1.20.4-1.6.17.jar
fabric-api-0.95.3+1.20.4.jar
lithium-fabric-mc1.20.4-0.12.1.jar
sodium-fabric-0.5.8+mc1.20.4.jar
sodium-extra-0.5.4+mc1.20.4-build.116.jar
modmenu-9.0.0.jar
fabric-carpet-1.20.3-1.4.128+v231205.jar

shaders:
config iris: 
[optionsshaders.txt](https://github.com/BelmuTM/Noble/files/14623525/optionsshaders.txt)

config minecraft:
[optionsof.txt](https://github.com/BelmuTM/Noble/files/14623527/optionsof.txt)
[user_jvm_args.txt](https://github.com/BelmuTM/Noble/files/14623528/user_jvm_args.txt)
[options.txt](https://github.com/BelmuTM/Noble/files/14623529/options.txt)
[config.zip](https://github.com/BelmuTM/Noble/files/14623530/config.zip)

config shader:
[Noble v1.6.4.zip.txt](https://github.com/BelmuTM/Noble/files/14623537/Noble.v1.6.4.zip.txt)

log:

**Comment by BelmuTM** [comment]
Hey again, I'm currently trying to fix the issue as best as I can, thanks for reporting it!

**Comment by BelmuTM** [comment]
Hello, the issue has been fixed in the latest official release!
https://modrinth.com/shader/noble/version/1.6.5

**Comment by SJK9906** [comment]
ok thank
