### ISSUE TITLE
no light

### ISSUE THREAD

**Issue by SJK9906** [BelmuTM/Noble#13]
if you set render mode

render mode:
![image](https://github.com/BelmuTM/Noble/assets/129201282/d36b7efb-097a-424b-9fb3-b8ba97e0cb05)

default mod:
![image](https://github.com/BelmuTM/Noble/assets/129201282/db12b200-f82d-42e1-93cc-50c795f65569)

video:
Uploading Minecraft_ 1.20.4 - Giocatore singolo 2024-03-19 21-56-07 (2).mp4…

other (Shrimple_v0.11/SEUS PTGI):
![image](https://github.com/BelmuTM/Noble/assets/129201282/67395d11-e98a-49e0-81b0-c8fe12494939)
![image](https://github.com/BelmuTM/Noble/assets/129201282/2d4097de-6362-4159-b5a8-07a842074232)

**Comment by BelmuTM** [comment]
That's normal, Noble's global illumination is screen space, if you want world space global illumination like SEUS PTGI has you can get it on my Patreon page starting from 5€/monthn.
https://www.patreon.com/Belmu
